server:
  port: 80
  context-path: /buliding/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/buliding_manage?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
    type: com.alibaba.druid.pool.DruidDataSource

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/dnp/bulidingmanage/dao/impl/*Mapper.xml
  typeAliasesPackage: com.dnp.bulidingmanage.model


  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true